name: "smtp-server"

services:
  smtp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: smtp-server
    hostname: smtp-server.io
    ports:
      - "2525:2525"
    volumes:
      - ../data/email_log:/app/email_log
    command: ["-ssl", "-as", "-f", "-ld", "/app/email_log"]
